const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('narc', {
  init: () => ipcRenderer.invoke('rec:init'),
  setReload: (on) => ipcRenderer.send('rec:set-reload', on),
  setPlay: (on) => ipcRenderer.send('rec:set-play', on),
  setHeight: (h) => ipcRenderer.send('rec:set-height', h),
  setBlur: (deg) => ipcRenderer.send('rec:set-blur', deg),
  viewport: () => ipcRenderer.invoke('rec:viewport'),
  onViewport: (cb) => ipcRenderer.on('rec:viewport', (_e, v) => cb(v)),
  onVelocity: (cb) => ipcRenderer.on('rec:velocity', (_e, v) => cb(v)),
  onPointer: (cb) => ipcRenderer.on('rec:pointer', (_e, p) => cb(p)),
  onCursorImage: (cb) => ipcRenderer.on('rec:cursor-image', (_e, img) => cb(img)),
  onCursor: (cb) => ipcRenderer.on('rec:cursor', (_e, c) => cb(c)),
  onCursorSpans: (cb) => ipcRenderer.on('rec:cursor-spans', (_e, spans) => cb(spans)),
  onAnimProgress: (cb) => ipcRenderer.on('rec:anim-progress', (_e, p) => cb(p)),
  source: () => ipcRenderer.invoke('rec:source'),
  open: () => ipcRenderer.invoke('rec:open'),
  write: (position, data) => ipcRenderer.send('rec:write', position, data),
  finish: (stats, take) => ipcRenderer.invoke('rec:finish', stats, take),
  cancel: (discarded) => ipcRenderer.invoke('rec:cancel', discarded),
  discard: (file) => ipcRenderer.invoke('rec:discard', file),
  state: (recording) => ipcRenderer.send('rec:state', recording),
  reload: () => ipcRenderer.send('rec:reload'),
  edit: () => ipcRenderer.send('rec:edit'),
  playAnimation: () => ipcRenderer.send('anim:play'),
  stopAnimation: () => ipcRenderer.send('anim:stop'),
  close: () => ipcRenderer.send('rec:close-pane'),
  onToggle: (cb) => ipcRenderer.on('rec:toggle', () => cb()),
  onStop: (cb) => ipcRenderer.on('rec:stop', () => cb()),
  onEvent: (cb) => ipcRenderer.on('rec:event', (_e, data) => cb(data)),
});
